# name: My First Workflow

# on:
#   push:
#     branches: [main]

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print message
#         run: echo "Hello, main first GitHub Action chala raha hoon!"



name: My First Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, main first GitHub Action chala raha hoon!"
      - name: Show event type
        run: echo "Ye workflow trigger hui: ${{ github.event_name }}"